---
title: Knipperen of pulseren van een LED lampje
hero_image: images/banner.png
description: Laat een LED knipperen of pulseren.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-08"
steps:
  - title: Laat een LED knipperen of pulseren
