title: Blink or pulse on LED
hero_image: images/banner.png
description: Make an LED blink or pulse.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-08"
steps:
  - title: Make an LED blink or pulse
